### ISSUE TITLE
Error in rule normalize : jobid 17

### ISSUE THREAD

**Issue by HannahDixon** [simonlabcode/bam2bakR#5] opened 2023-06-24 20:23 UTC
Dear Isaac, 

I am really interested in using bam2bakR - however I am running into some problems. I have managed to produce files for sf_reads but I encounter an error at jobID 17 - in rule normalise. The log file does not contain any information. Sort_filter logs look normal. Htseq log does say: 
* HTSeq counting finished for sample KD_1
* HTSeq .sam files merged for sample KD_1
awk: fatal: cannot open file `./results/htseq/KD_1_GF_htseq.*_temp.txt' for reading (No such file or directory). 

the Main Error message: 
Error in rule normalize:
    jobid: 17
    input: results/htseq/WT_1_tl.bam, results/htseq/WT_ctl_tl.bam, results/htseq/KD_1_tl.bam, results/htseq/KD_ctl_tl.bam
    output: results/normalization/scale
    log: logs/normalize/normalize.log (check log file(s) for error details)
    conda-env: /Volumes/TOSHIBA_EXT/Snakemake/.snakemake/conda/309b5cf13b2739818b588fc7df515eaa_
    shell:
        
            chmod +x /Users/u1984277/Library/Caches/snakemake/snakemake/source-cache/runtime-cache/tmpzygticav/https/raw.githubusercontent.com/simonlabcode/bam2bakR/main/workflow/scripts/normalize.R
            /Users/u1984277/Library/Caches/snakemake/snakemake/source-cache/runtime-cache/tmpzygticav/https/raw.githubusercontent.com/simonlabcode/bam2bakR/main/workflow/scripts/normalize.R --dirs ./results/htseq/ --spikename ""
            mv scale results/normalization/scale
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Have you encountered this before? 
Thanks, 
Hannah
[KD_1.log](http
[KD_1.log](https://github.com/simonlabcode/bam2bakR/files/11858085/KD_1.log)
s://github.com/simonlabcode/bam2bakR/files/11858084/KD_1.log)
[KD_1.log](https://github.com/simonlabcode/bam2bakR/files/11858086/KD_1.log)

**Comment by isaacvock** [comment] 2023-06-24 21:19
Hello Hannah,

I'm sorry that you ran into problems. I have seen this error before but it has multiple possible sources. To help you diagnose the cause in this case, can you please send the following information:

1) Your config.yaml file. Github doesn't allow sending of yaml files for some reason,  so you can either zip,  copy the contents into a text file, etc.
2) Is the Htseq log file you sent the full log file for that step + sample? If so, then it looks like htseq didn't even run, which is instructive,  but if not, can you send the full log file?
3) If possible, a downsampled version of one of your bam files would be incredibly helpful in reproducing the error.  Perhaps with only 1% of the reads (which can be generated by running samtools view -b -s 0.01 input_bam_file.bam >  subsampled_bam_name.bam) or less, whatever gets it to a manageable enough size to send.

I apologize for hassling you to provide all of this information, but it will be incredibly helpful. 

Best regards,
Isaac

**Comment by isaacvock** [comment] 2023-06-25 01:59
As an aside that could save you some time, my best guess right now (if the HTSeq log file you showed is the complete log file) is that the path to your annotation file is misspecified in the config.yaml file, as it seems like HTSeq was not able to find the provided gtf file path. Thus, it might be worth double checking that the path is specified in the manner discussed in the bam2bakR documentation.

**Comment by HannahDixon** [comment] 2023-06-25 08:34
Hi Isaac, 

You are absolutely spot on. The path to my gtf file had a typo, which I spotted in the log file for the htseq as you mention.  Corrected it and now its 100% run smoothly! Thank you so much. 

Hannah

**Closed as completed** 2023-06-25 08:35 UTC
